AI_Gaming_Research:
  - https://arxiv.org/rss/cs.HC
  - https://www.jair.org/index.php/jair/gateway/plugin/WebFeedGatewayPlugin/rss2
  - https://gameanalytics.com/blog/feed/
  - http://www.gamesbrief.com/feed/
  - https://www.gamedeveloper.com/rss.xml
